name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./OrderAndPayment/pom.xml
          mvn clean package -f ./RestaurantManagement/pom.xml
          mvn clean package -f ./DeliveryManagement/pom.xml

      - name: Docker Build and push for OrderAndPayment
        uses: docker/build-push-action@v4
        with:
          context: ./OrderAndPayment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/orderandpayment:latest
            ghcr.io/${{ github.repository }}/orderandpayment:${{ github.ref_name }}
            
      - name: Docker Build and push for RestaurantManagement
        uses: docker/build-push-action@v4
        with:
          context: ./RestaurantManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/restaurantmanagement:latest
            ghcr.io/${{ github.repository }}/restaurantmanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for DeliveryManagement
        uses: docker/build-push-action@v4
        with:
          context: ./DeliveryManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deliverymanagement:latest
            ghcr.io/${{ github.repository }}/deliverymanagement:${{ github.ref_name }}
            
