apiVersion: v1
kind: Service
metadata:
  name: RestaurantManagement
  labels:
    app: RestaurantManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: RestaurantManagement