server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: OrderAndPayment
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, /payments/**, /orderNotifications/**, /orderSummaries/**, /orderDetails/**, /paymentSummaries/**, /paymentDetails/**, /orderNotificationSummaries/**
        - id: RestaurantManagement
          uri: http://localhost:8083
          predicates:
            - Path=/restaurants/**, /menus/**, /newOrders/**, /menuLists/**
        - id: DeliveryManagement
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**, /assignedDeliveryOrders/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: OrderAndPayment
          uri: http://orderAndPayment:8080
          predicates:
            - Path=/orders/**, /payments/**, /orderNotifications/**, 
        - id: RestaurantManagement
          uri: http://restaurantManagement:8080
          predicates:
            - Path=/restaurants/**, /menus/**, 
        - id: DeliveryManagement
          uri: http://deliveryManagement:8080
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
