---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderAndPayment
  labels:
    app: OrderAndPayment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderAndPayment
  template:
    metadata:
      labels:
        app: OrderAndPayment
    spec:
      containers:
        - name: OrderAndPayment
          image: username/OrderAndPayment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: RestaurantManagement
  labels:
    app: RestaurantManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RestaurantManagement
  template:
    metadata:
      labels:
        app: RestaurantManagement
    spec:
      containers:
        - name: RestaurantManagement
          image: username/RestaurantManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeliveryManagement
  labels:
    app: DeliveryManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DeliveryManagement
  template:
    metadata:
      labels:
        app: DeliveryManagement
    spec:
      containers:
        - name: DeliveryManagement
          image: username/DeliveryManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: OrderAndPayment
  labels:
    app: OrderAndPayment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: OrderAndPayment


---


apiVersion: v1
kind: Service
metadata:
  name: RestaurantManagement
  labels:
    app: RestaurantManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: RestaurantManagement


---


apiVersion: v1
kind: Service
metadata:
  name: DeliveryManagement
  labels:
    app: DeliveryManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DeliveryManagement

